default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: <%= ENV['DB_PW'] %>
  host: localhost
  pool: 5
  timeout: 5000
  port: 3306

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
